rails-real-ru/files/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :vehicles
end

rails-real-ru/files/app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  # BEGIN
  has_one_attached :image
  # END

  validates :manufacture, presence: true
  validates :model, presence: true
  validates :color, presence: true
  validates :doors, presence: true, numericality: { only_integer: true }
  validates :kilometrage, presence: true, numericality: { only_integer: true }
  validates :production_year, presence: true

  # BEGIN
  validates :image,
            attached: true,
            content_type: %i[png jpg jpeg],
            size: { less_than: 5.megabytes }
  # END
end

rails-real-ru/files/app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end

  def show
    @vehicle = Vehicle.find params[:id]
  end

  def new
    @vehicle = Vehicle.new
  end

  def edit
    @vehicle = Vehicle.find params[:id]
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      redirect_to @vehicle, notice: 'Vehicle was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @vehicle = Vehicle.find params[:id]

    if @vehicle.update(vehicle_params)
      redirect_to @vehicle, notice: 'Vehicle was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @vehicle = Vehicle.find params[:id]

    @vehicle.destroy

    redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.'
  end

  private

  # Only allow a list of trusted parameters through.
  def vehicle_params
    params.require(:vehicle).permit(
      :manufacture,
      :model,
      :color,
      :doors,
      :kilometrage,
      :production_year,
      :image
    )
  end
end

rails-real-ru/files/app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title = t('.title')
    == csrf_meta_tags
    == csp_meta_tag
    meta name="keywords" content="template language"
    meta name="author" content='author'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  body.d-flex.flex-column.h-100

    = render 'layouts/shared/nav'

    = render 'layouts/shared/flash'

    main
      .mt-4.mb-5.pb-5
        .container
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .mb-4
              h2 = yield :title

            == yield

    footer.bg-dark.text-light.mt-auto
      .container-xl
        .row.py-2
          = t('.hexlet_title', year: Time.current.year)

rails-real-ru/files/app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |_type, msg|
      .alert.alert-info
        = msg

rails-real-ru/files/app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light
      a.navbar-brand.me-md-4(href='/')
        = image_tag asset_pack_path('media/images/logo.png'), width: 30, alt: t('.hexlet_logo')

      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav
          li.nav-item.me-2
            = link_to t('.home'), root_path, class: 'nav-link link-dark'
          li.nav-item.me-2
            = link_to t('.vehicles'), vehicles_path, class: 'nav-link link-dark'